### ISSUE TITLE
Adding Osmocom source/sink for gnuradio v3.7

### ISSUE THREAD

**Issue by haniyrasul** [git-artes/docker-gnuradio#9]
try this code in command line:
`$ sudo apt-get install gr-osmosdr`

Thanks @git-artes for the help. 🙌

**Comment by git-artes** [comment]
In order to avoid repeating this step every time you start the container, you may add gr-osmosdr (and all the extra packages you may need) in line 29 (or wherever feels right for you) of the Dockerfile. As: 
`
RUN apt-get install -y gnuradio-dev cmake git libboost-all-dev libcppunit-dev liblog4cpp5-dev swig liborc-dev gr-osmosdr
`

You have to re-build the image, but that's necessary just once.

In any case, I'll close this since you've solved it.

best
